# Generated by Django 4.2.6 on 2023-11-08 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_games_price'),
        ('shop', '0002_factures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='games',
            field=models.ManyToManyField(blank=True, to='games.games'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_shop', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('games', models.ManyToManyField(to='games.games')),
            ],
        ),
    ]
