# Generated by Django 4.2.6 on 2023-10-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genders',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='calification',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='sellers',
            field=models.IntegerField(blank=True),
        ),
    ]
