# Generated by Django 4.2.6 on 2023-10-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_developers_baner_image_developers_perfil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='baner_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='port_image',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
