# Generated by Django 4.2.6 on 2023-11-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_games_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
