# Generated by Django 4.2.6 on 2023-11-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_perfil',
            field=models.CharField(blank=True, default='https://thumbs.dreamstime.com/b/perfil-de-usuario-vectorial-avatar-predeterminado-179376714.jpg', max_length=400),
        ),
    ]
